
disable_response_storage = true
model = "gpt-5.3-codex"
model_reasoning_effort = "high"
personality = "pragmatic"
sandbox_mode = "danger-full-access"

[projects."/Users/qiushi"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/music-mvp-frontend-new"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/content-engine"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/aloe/itell"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/slides"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/vercel-ai"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/multimodal-engine"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/preprocessing-engine"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/next-music"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/canva-clone"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/remotion-examples/remotion-hello"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/marswave/listenhub-fe"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/learn-swift/Swift101.playground"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/aloe/itell-rs"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/cc-prep"]
trust_level = "trusted"

[projects."/Users/qiushi/workspace/TabType"]
trust_level = "trusted"

[mcp_servers.chrome-devtools]
command = "npx"
args = [ "chrome-devtools-mcp@latest" ]

[mcp_servers.context7]
command = "npx"
args = [ "-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-fc0f95a3-ef46-4023-ba6e-9c1f3eda4dbe" ]
startup_timeout_sec = 40

[tools]
view_image_tool = true

[features]
web_search = true
collaboration_modes = true

[notice]
hide_gpt5_1_migration_prompt = true
suppress_unstable_features_warning = true

